version: "3.7"

services:
  esdb:
    image: eventstore/eventstore:latest
    container_name: esdb-node
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    restart: unless-stopped
    networks: 
      - esproj-network
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  esproj:
    image: esproj:latest
    container_name: esproj-node
    restart: unless-stopped
    networks: 
      - esproj-network
    ports:
      - "127.0.0.1:5001:5000"

networks:
  esproj-network:
    name: esproj-network

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: